### ISSUE TITLE
[tesserini] errore bloccante

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#282]
Accedendo in Gaia > Soci > tesserini > richiedi tesserino otteniamo

Errore 500.

Problema bloccante.

**Comment by yakky** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta è disponibile un tracciato più dettagliato dell'errore?

**Comment by AlfioEmanueleFresta** [comment]
Controllo.

**Comment by AlfioEmanueleFresta** [comment]
Error message
builtins:AttributeError: 'NoneType' object has no attribute 'upper'

Stack trace
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
**File "./autenticazione/funzioni.py", line 118, in _pagina_privata
File "./ufficio_soci/viste.py", line 1156, in us_tesserini_richiedi**
File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 700, in save
File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 728, in save_base
File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 812, in _save_table
File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 851, in _do_insert
File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 122, in manager_method
File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 1039, in _insert
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 1059, in execute_sql
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 1019, in as_sql
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 1019, in <listcomp>
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 1018, in <listcomp>
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 958, in prepare_value
File "/usr/local/lib/python3.4/dist-packages/django/db/models/fields/__init__.py", line 728, in get_db_prep_save
File "/usr/local/lib/python3.4/dist-packages/django/db/models/fields/__init__.py", line 720, in get_db_prep_value
File "/usr/local/lib/python3.4/dist-packages/django/db/models/fields/__init__.py", line 1112, in get_prep_value
**File "./base/utils.py", line 163, in to_python**

**Comment by yakky** [comment]
@AlfioEmanueleFresta guarda la PR allegata

**Comment by yakky** [comment]
Scusate, chiuso per errore
