### ISSUE TITLE
[sedi] errore 500

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#317]
Riscontriamo quanto segue:

URL /informazioni/sedi/italia-lazio-dellarea-metropolitana-roma-capitale-/
HTTP referrer   https://gaia.cri.it/informazioni/sedi/italia-lazio/

TRACE

Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in **iter**
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in **call**
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in **call**
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/clickjacking.py", line 58, in wrapped_view
File "./autenticazione/funzioni.py", line 43, in _pagina_pubblica
File "./base/viste.py", line 247, in informazioni_sede
File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 155, in get_object_or_404
File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 391, in get

**Comment by yakky** [comment]
@PaoloGiustiniani seguendo il link dalla pagina https://gaia.cri.it/informazioni/sedi/italia-lazio/ non riesco a riprodurre il problema. qual è la descrizione esatta dell'eccezione?
Il link riportato è "/informazioni/sedi/italia-lazio-dellarea-metropolitana-roma-capitale-/" (notare il "-" in fondo) forse è stato inserito manualmente da qualche parte?

**Comment by yakky** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta lo slug è troppo corto e quindi ci sono più sedi con lo stesso slug.
Va aumentato lo slug e salvate tutte le sedi con una datamigration per aggiornare tutti gli slug

**Comment by PaoloGiustiniani** [comment]
@yakky https://gaia.cri.it/informazioni/sedi/italia-lazio-dellarea-metropolitana-roma-capitale-/

**Comment by PaoloGiustiniani** [comment]
Verifico il - se è nel BE

**Comment by PaoloGiustiniani** [comment]
Scusate, l'utente ci segnala che lo ha messo lui per errore il trattino.

**Comment by yakky** [comment]
@AlfioEmanueleFresta @PaoloGiustiniani in realtà secondo me è una segnalazione valida

**Comment by PaoloGiustiniani** [comment]
dalla mappa non rimanda a questo URL, bensì a https://gaia.cri.it/informazioni/sedi/italia-lazio-dellarea-metropolitana-roma-capitale/

**Comment by yakky** [comment]
sì ma ad es "Comitato Municipio 6 di Roma " ha lo stesso errore perché il suo slug viene troppo lungo e rimane tagliato, così come quelli di altri e ``get_object_or_404`` restituisce errore

**Comment by PaoloGiustiniani** [comment]
Riapro.

**Comment by yakky** [comment]
@PaoloGiustiniani quale priorità ha questa segnalazione?

**Comment by PaoloGiustiniani** [comment]
@yakky per ora 0.

@matthewmazzoleni qualora arrivassero ulteriori segnalazioni su HD aumentiamo ad 1.

**Comment by yakky** [comment]
@PaoloGiustiniani con la sistemazione comitati #521 mi sembrerebbe sistemato. puoi verificare?

**Comment by yakky** [comment]
@PaoloGiustiniani @matthewmazzoleni  potete verificare se è stato risolto da #521 ? Gli slug sono cambiati e ora non ci sono più conflitti di slug.
Se non avete niente in contrario la chiuderei se entro 3~4 giorni non ci sono esempi contrari

**Comment by PaoloGiustiniani** [comment]
Direi che è stata risolta con #521.
