### ISSUE TITLE
ValueError: Cannot use QuerySet for "sede": Use a QuerySet for "Area".

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#339]
builtins:ValueError: Cannot use QuerySet for "sede": Use a QuerySet for "Area".
in
/utente

COUNT
15 similar errors to this
in the last 6 hours

```
Stack trace
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 109, in _pagina_privata
File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 205, in inner
File "./autenticazione/models.py", line 123, in applicazioni_disponibili
File "./anagrafica/models.py", line 498, in applicazioni_disponibili
File "./anagrafica/models.py", line 571, in ha_permesso
File "./anagrafica/permessi/persona.py", line 153, in persona_ha_permesso
File "./anagrafica/models.py", line 1626, in permessi
File "./anagrafica/permessi/delega.py", line 12, in delega_permessi
File "./anagrafica/permessi/funzioni.py", line 224, in permessi_delegato_area
File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 122, in manager_method
File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 790, in filter
File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 808, in _filter_or_exclude
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py", line 1243, in add_q
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py", line 1269, in _add_q
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py", line 1174, in build_filter
File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/query.py", line 1068, in check_related_objects
```

**Comment by yakky** [comment]
@AlfioEmanueleFresta come è possibile replicare questo errore? Hai dati di contesto per provare a riprodurre l'errore?

**Comment by yakky** [comment]
Ad una prima occhiata per uno o più utenti è stata creata in modo non corretto una delega di delegato di area ma il cui oggetto è una o più sedi.

**Comment by AlfioEmanueleFresta** [comment]
@biagiosaitta?

**Comment by biagiosaitta** [comment]
Ho controllato su un utente in cui si verificava l'errore, ed era nominata delegata d'area su un'unità territoriale. L'ho modificato in delegato d'obiettivo e il login funziona, però non gli permette la creazione di attività! @AlfioEmanueleFresta
