### ISSUE TITLE
Migliorare il sistema di posta

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#345]
L'emergenza terremoto ha portato alla luce alcune criticita' nell'attuale gestione della coda di posta, che e' stata messa sotto estremo stress. Il sistema deve essere in grado di gestire tali emergenze, quindi e' necessario apportare delle modifiche al sistema di smistamento. Qui dettaglio in parte delle specifiche per le modifiche da apportare.

Queste specifiche assumono un supporto infrastrutturale con un endpoint SMTP in grado di smistare tutta la posta che gli viene sbattuta contro -- che e' una fair assumption dato che il fallimento non e' stato dovuto dal server SMTP.

Attualmente il sistema di posta funziona piu' o meno cosi:

* Ogni 5 minuti, il cron chiama il metodo statico Messaggio.smaltisci_coda

  * Questo metodo raccoglie un numero (attualmente 1500) di `Messaggio`s in coda. Nota che questo ha un numero indefinito di destinatari per ogni messaggio. Per ognuno, il metodo `Messaggio.invia` viene chiamato. Viene passata come argomento la connessione SMTP per evitare che il metodo debba aprirne una nuova.

    * Questo provvede a ciclare sui destinatari con `inviato=False` ed effettuare l'invio. Per ogni destinatario correttamente smistato, `inviato` diventa `True`. Una volta terminato, applica uno stato `terminato` al messaggio. 

Problemi attuali:

* Se una eccezione su un destinatario termina l'invio di un messaggio, la prossima iterazione non continuera' dal destinatario sbagliato ma riprovera' tutti quelli nel messaggio con inviato=False. Questi contengono anche errori che non dovrebbero essere riprovati, tipo e-mail non valide, perdendo un sacco di tempo. Inoltre il server SMTP ci disconnette automaticamente ogni tot di e-mail non valide, e questo puo' vuol dire che per grandi messaggi, e' praticamente garantito che il messaggio debba riessere messo in coda piu' volte.

* Se la coda lascia piu' di 1500 messaggi non terminati, e' possibile che provi all'infinito ad inviare quei 1500, senza accettare e smistare i nuovi messaggi. Deve essere introdotto un nuovo sistema di stati per i messaggi, che diano uno stato piu' significativo ai messaggi in coda. In particolare, una tupla configurabile dovrebbe permettere di configurare quali errori dovrebbero portare al riprovare e quali invece ad un nuovo tentativo. Ad esempio, e-mail invalida o errori generici ritornati da SMTP dovrebbero NON rimettere in coda il messaggio, mentre un errore temporaneo di invio o una disconnessione dal server SMTP (che accade di tanto in tanto e deve essere tollerata) dovrebbe riportare il messaggio in coda. Infine, il messaggio dovrebbe avere dei dati aggregati sulla situazione di invio che dovrebbero essere usati per identificare velocemente lo stato di invio del messaggio.

* Ci sono delle eccezioni di tipo AttributeError da qualche parte quando in una riga si aggiunge qualcosa tipo `[x.persona.email],` dove `.email` non esiste per quella persona.

Altre note:

* La modifica non deve rimettere in coda dei messaggi che sono stati in errore per piu' di una settimana. Questi non devono neanche andare cancellati dal database.

------

Rimango a disposizione per eventuali chiarimenti. Il codice e' tutto nel modulo `posta`, in particolare distribuito in `models.py`.

**Comment by yakky** [comment]
@AlfioEmanueleFresta dopo una prima analisi (vedi https://github.com/nephila/jorvik/blob/feature/test_posta/posta/tests.py#L105) penso che la soluzione migliore sia:
- gestire i fallimenti di invio secondo le specifiche SMTP: ovvero trattando gli errori 5XX come "fatali" e gli errori 4XX come temporanei
- in base a quanto sopra marcare opportunamento i destinatari. In caso di ``SMTPRecipientsRefused`` il messaggio viene considerato consegnato se almeno uno dei due indirizzi del destinatario è andato a buon fine (https://github.com/nephila/jorvik/blob/feature/test_posta/posta/models.py#L187)
- un messaggio viene considerato in coda se ha almeno un destinatario non inviato (nel senso di "mai tentato") o con fallimenti temporanei. Se un messaggio contiene solo destinatari inviati e con fallimenti permanenti non è più considerato in coda
- quando il messaggio viene rimesso in coda gli viene assegnato un tempo prima del quale **non** ritentare gli invii; l'intervallo cresce ad ogni tentativo di invio in modo casuale (es: selezionando l'intervallo in un insieme di numeri primi di minuti moltiplicato per il numero di tentativi); questa casualità fa sì che più il messaggio è "vecchio" (ovvero con più fallimenti temporanei) meno sia rimesso in coda a favore di altri "recenti"

**Comment by AlfioEmanueleFresta** [comment]
@yakky mi piace, per favore corredate di test. 

Al momento la maggior parte dei cron falliscono con seguente errore:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django_cron/management/commands/runcrons.py", line 62, in run_cron_with_cache_check
    manager.run(force)
  File "/usr/local/lib/python3.4/dist-packages/django_cron/__init__.py", line 214, in run
    self.msg = self.cron_job.do()
  File "/home/gaia/jorvik/posta/cron.py", line 14, in do
    Messaggio.smaltisci_coda(dimensione_massima=1500)
  File "/home/gaia/jorvik/posta/models.py", line 291, in smaltisci_coda
    messaggio.invia(connection)
  File "/home/gaia/jorvik/posta/models.py", line 153, in invia
    destinatari = [d.persona.email]
AttributeError: 'NoneType' object has no attribute 'email'
```

Riusciamo a mandare un fix? Per questa eccezione, anche in giornata senza test va bene.

**Comment by yakky** [comment]
@AlfioEmanueleFresta Certamente

**Comment by yakky** [comment]
Ho pronto ho hotfix per gestire il caso specifico, seguirà patch più completa

**Comment by AlfioEmanueleFresta** [comment]
Ta. /cc @PaoloGiustiniani

**Comment by PaoloGiustiniani** [comment]
come siamo messi con questa issue?

**Comment by PaoloGiustiniani** [comment]
Purtroppo riceviamo segnalazioni da tutta Italia, non è più possibile erogare tale tipologia di servizio finchè non sarà trovata una soluzione al problema.

Le email vengono recapitate 4/5/6 volte allo stesso mittente, questo causa problemi di varia natura:
- stiamo  finendo costantemente in numerose blacklist;
- gli utenti sono esasperati da questa situazione.

Vi chiedo di **BLOCCARE/INIBIRE** l'invio massivo di ogni comunicazione specificando all'utente che la casistica è in gestione (vi pregherei di fornire il link  di questa issue).

_Possibilmente entro oggi._

Grazie.

**Comment by AlfioEmanueleFresta** [comment]
Confermo che il problema e' relativo al flag impostato su `inviato` che viene disperso al termine del lavoro, o all'occorrenza qualunque eccezione, come suggerito nel mio primo commento a fine agosto:

Aggiungo a quanto detto da @PaoloGiustiniani, per favore la modifica fatela nella vista degli elenchi (il template web per intenderci che viene caricato per tutti gli elenchi) -- questo la propaghera' velocemente su tutti gli elenchi massivi di Gaia.

@yakky sono state smaltite 7 issue con priorita' minore prima di questa in milestone, che e' qui da fine agosto. Per reiterare, l'ordine delle priorita' e': 0, 1, 2, 3, Urgente.

**Comment by yakky** [comment]
@AlfioEmanueleFresta ho un branch a cui sono stati aggiunti dei test, ma non abbiamo nessun set significativo di dati su cui far girare i test per cui qualunque soluzione si trovi rimane comunque non testata adeguatamente.
Posso aprire una PR con lo stato attuale, ma rimane comunque poco soddisfacente.

**Comment by AlfioEmanueleFresta** [comment]
@yakky comprendo che testare senza dei dati reali, o accesso al server di produzione, e' problematico e rallenta la fase di analisi. 

Allo stesso tempo questo non puo' fermare lo sviluppo. In questo caso, mi permetto di aggiungere, le eccezioni da lanciare sono ben elencate nel codice[1], e l'interfaccia per i backend di posta di Django ha esattamente 3 metodi di cui 2 opzionali[2], quindi lo sviluppo di un email mock backend di test, per simulare il comportamento del server di posta (anche lanciando eccezioni a caso), e' giustificato. 

Credo di capire sia quello di cui mi parlavi a fine agosto:

> @yakky: faccio una review, e nelk frattempo cerco di creare un modo per riempire la coda
> @yakky: così da simulare i vari casi 
> @yakky: preliminarmente lavoro su un metodo per poter fare dei test sui casi anomali della posta così da poter procedere più speditamente poi nei fix

Possiamo questo avanti con priorita' urgente come parte di questo issue?

In conclusione, se in dubbio, chiedete! Sono qui per questo.

[1] https://github.com/CroceRossaItaliana/jorvik/blob/9ffbd41478fc2c3765e47d23a7059e83ae255327/posta/models.py#L191
[2] https://docs.djangoproject.com/en/1.10/topics/email/#defining-a-custom-email-backend

**Comment by PaoloGiustiniani** [comment]
Qualora sia presente il sospetto che #415 non risolva il problema **è necessario bloccare** la funzionalità di invio massivo.

Grazie.

**Comment by yakky** [comment]
@PaoloGiustiniani in gaia la distinzione è fra invio immediato e invio in coda. Forse per il momento si può bloccare l'invio dei messaggi dalla coda che in generale sono le notifiche più massive, mentre il primo metodo è generalmente usato per gli invii puntuali.
Il blocco però si fa semplicemente bloccando il cron sul server

**Comment by AlfioEmanueleFresta** [comment]
@yakky:

> Aggiungo a quanto detto da @PaoloGiustiniani, per favore la modifica (disattivare l'invio) fatela nella vista degli elenchi (il template web per intenderci che viene caricato per tutti gli elenchi) -- questo la propaghera' velocemente su tutti gli elenchi massivi di Gaia.

La giustificazione e' che il problema e' solo relativo agli invii con un grandissimo numero di destinatari -- ovvero gli invii che vengono dagli elenchi -- piuttosto che da ogni messaggio in coda.

/cc @PaoloGiustiniani

**Comment by yakky** [comment]
@AlfioEmanueleFresta quindi disabilitiamo solo l'opzione per l'utente dell'invio email dagli elenchi, ho capito bene?

**Comment by yakky** [comment]
@AlfioEmanueleFresta @PaoloGiustiniani intendo #416

**Comment by AlfioEmanueleFresta** [comment]
@yakky Si.

**Comment by yakky** [comment]
@AlfioEmanueleFresta Faccio il merge di #416 al termine dei test

**Comment by AlfioEmanueleFresta** [comment]
Piuttosto che nascondere del tutto il tasto, puoi invece aggiungere classe 'disabled' al pulsante per ingrigirlo, e onclick far spuntare:

```
alert("Siamo spiacenti, l'invio di e-mail massive e' temporaneamente disabilitato. Stiamo lavorando per risolvere il problema il piu' velocemente possibile.'); return false;
```

O simile? Giusto per dare una indicazione che l'invio e' temporaneamente disabilitato, altrimenti la gente comincia a scrivere al supporto perche' Gaia e' rotto / abbiamo tolto per sempre l'invio di massa.

**Comment by yakky** [comment]
Fatto il merge come da indicazioni.
Rimane da capire se #415 è un passo avanti per la soluzione del problema

**Comment by AlfioEmanueleFresta** [comment]
@yakky grazie. Mandato in produzione /cc @PaoloGiustiniani

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta allego quanto riscontrato questa notte: 3 email al medesimo aspirante, il contenuto è sempre lo stesso e riguarda un singolo corso di accesso:

![img_9612](https://cloud.githubusercontent.com/assets/5826472/19340075/5601c3c6-9127-11e6-99f1-ec1f77f2924a.PNG)

non escludo che ne possano arrivare altre.
/cc @PaoloGiustiniani

**Comment by yakky** [comment]
@AlfioEmanueleFresta  @PaoloGiustiniani  ci sono feedback sulla nuova gestione della coda?

**Comment by luca-dex** [comment]
Io ho mandato una email da ufficio soci ieri sera verso le 22 a 246
destinatari e non è ancora arrivato nulla. Siamo a quasi 12 ore.

**Comment by yakky** [comment]
@luca-dex intendi che non sono tornate indietro messaggi doppi-tripli ed errori in genere?

**Comment by PaoloGiustiniani** [comment]
@yakky @AlfioEmanueleFresta chiedo al centro di supporto se hanno segnalazioni in merito.

**Comment by PaoloGiustiniani** [comment]
@yakky la mail risulta non inviata lato gaia, ultimo tentativo non valorizzato, sembra che non sia stata presa in carico dal cron.

**Comment by yakky** [comment]
@PaoloGiustiniani nessun errore su new relic?

**Comment by PaoloGiustiniani** [comment]
@yakky verifico, inoltre anche le notifiche dei corsi base sono bloccate.

**Comment by PaoloGiustiniani** [comment]
@yakky non vedo errori, attendiamo @AlfioEmanueleFresta

**Comment by luca-dex** [comment]
@yakky intendo che non è proprio arrivato nulla a destinazione. Il messaggio su gaia risulta ancora in coda.

**Comment by yakky** [comment]
@luca-dex sì, avevo capito dai successivi messaggi di paolo.
Test in locale non riportano errori o blocchi della coda
Il cron gira? E' possibile far partire manualmente il cron con ``./manage.py runcrons "posta.cron.CronSmaltisciCodaPosta"`` ?

**Comment by PaoloGiustiniani** [comment]
@yakky output
```

2016-10-19 11:25:52.311318 == ricerca messaggi da smaltire, coda=2200
2016-10-19 11:25:52.311353 apro connessione al backed di invio posta
2016-10-19 11:25:52.960874 invio messaggio id=560074, destinatari=(totale=462, in_attesa=7)
```

**Comment by PaoloGiustiniani** [comment]
@yakky @AlfioEmanueleFresta il cron è di nuovo rotto!

`76984621': (501, b'<3476984621>: recipient address must contain a domain')}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django_cron/management/commands/runcrons.py", line 62, in run_cron_with_cache_check
    manager.run(force)
  File "/usr/local/lib/python3.4/dist-packages/django_cron/__init__.py", line 214, in run
    self.msg = self.cron_job.do()
  File "/home/gaia/jorvik/posta/cron.py", line 14, in do
    Messaggio.smaltisci_coda(dimensione_massima=2200)
  File "/home/gaia/jorvik/posta/models.py", line 314, in smaltisci_coda
    messaggio.invia(connection)
  File "/home/gaia/jorvik/posta/models.py", line 195, in invia
    if any([list(item.values())[0] == 250 for item in e.recipients]):
  File "/home/gaia/jorvik/posta/models.py", line 195, in <listcomp>
    if any([list(item.values())[0] == 250 for item in e.recipients]):
AttributeError: 'str' object has no attribute 'values'
`

**Comment by yakky** [comment]
@PaoloGiustiniani ok, ci guardiamo subito

**Comment by yakky** [comment]
@PaoloGiustiniani il fix sopra dovrebbe risolvere questo errore.
Aspettiamo che finiscano i test e ne faccio il merge

**Comment by yakky** [comment]
@PaoloGiustiniani merge fatti

**Comment by yakky** [comment]
@PaoloGiustiniani miglioramenti?

**Comment by PaoloGiustiniani** [comment]
@yakky ora è in produzione, vediamo che succede

**Comment by luca-dex** [comment]
Mi è arrivata l'email di ieri sera

**Comment by PaoloGiustiniani** [comment]
Dalle code di posta vedo la stessa email - verso lo stesso destinatario - anche 5-6 volte.

**Comment by yakky** [comment]
@luca-dex @PaoloGiustiniani @AlfioEmanueleFresta  bisognerebbe riuscire a modellare il traffico di posta con dei casi d'uso su luke su cui noi possiamo operare per capire il motivo di queste duplicazioni

**Comment by luca-dex** [comment]
Mi è appena arrivata 5 volte la stessa email che ho spedito questa mattina :sob:

**Comment by yakky** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta se siete d'accordo preparerei una verisione che fa un log "estremo" di quello che succede nella coda di posta e che viene salvato da parte e lo deployamo live, così da quello proviamo a capire cosa succede.

**Comment by PaoloGiustiniani** [comment]
@yakky ok per il log, qualora richiedesse molto tempo stoppiamo il servizio di mail massive

**Comment by yakky** [comment]
@PaoloGiustiniani conto di averlo disponibile in serata

**Comment by luca-dex** [comment]
Qualche risultato dall'analisi dei log? @PaoloGiustiniani @yakky

**Comment by luca-dex** [comment]
Nella giornata di ieri è successo questo:

- è stata inviata una email massiva a circa 15630 utenti
- come in passato il sistema di invio ha iniziato a recapitare email duplicate, triplicate, insomma siamo arrivati ad avere fino ad 8 email ricevuta dalla stessa persona

In sostanza con il lavoro svolto c'è stato un miglioramento, ma la problematica è lontana dall'essere risolta, nonostante le ore di lavoro spese su questa issue.

@PaoloGiustiniani sta verificando se i log ci sono e nel caso li trasmetterà così che possano essere analizzati.

Di seguito riporto ciò che ho ricevuto io, fortunatamente solo 3 copie:

![whatsapp image 2016-11-25 at 23 02 03](https://cloud.githubusercontent.com/assets/3315913/20639554/7bee765c-b3c7-11e6-9d70-50988282e6cc.jpeg)

**Comment by PaoloGiustiniani** [comment]
@yakky @luca-dex ho inviato tutto tramite email.

**Comment by luca-dex** [comment]
@yakky come si legge questo frammento del log, tenendo conto che:
- a me l'email è arrivata 3 volte
- l'orario a cui mi è arrivata è 18:32
- nel log compare questa dicitura che non comprendo: `Hash destinatari=-9162579471349130760luca.desano`

```
[...]
DEBUG 2016-11-25 18:32:04,083 posta MSG 746204: Num=1 Destinatari=4076407
DEBUG 2016-11-25 18:32:04,083 posta MSG 746204: Hash destinatari=-6103510294764993726
DEBUG 2016-11-25 18:32:04,103 posta MSG 746204: salvataggio destinatario=4076408
DEBUG 2016-11-25 18:32:04,105 posta MSG 746204: termine invio successo=False, inviato=True invalido=False errore=None
DEBUG 2016-11-25 18:32:04,112 posta MSG 746204: Num=1 Destinatari=4076407
DEBUG 2016-11-25 18:32:04,112 posta MSG 746204: Hash destinatari=-8742412366959259733
DEBUG 2016-11-25 18:32:04,122 posta MSG 746204: salvataggio destinatario=4076408
DEBUG 2016-11-25 18:32:04,124 posta MSG 746204: termine invio successo=False, inviato=True invalido=False errore=None
DEBUG 2016-11-25 18:32:04,129 posta MSG 746204: Num=1 Destinatari=4076407
DEBUG 2016-11-25 18:32:04,129 posta MSG 746204: Hash destinatari=-9162579471349130760luca.desano
DEBUG 2016-11-25 18:32:04,161 posta MSG 746204: salvataggio destinatario=4076407
DEBUG 2016-11-25 18:32:04,165 posta MSG 746204: termine invio successo=False, inviato=True invalido=False errore=None
[...]
```

**Comment by yakky** [comment]
@PaoloGiustiniani @luca-dex @AlfioEmanueleFresta si riesce ad avere una situazione aggiornata in cui si possa riprodurre i problemi di invio multiplo?

**Comment by yakky** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta questa segnalazione è ancora sensata? C'è qualcosa da gestire?

**Comment by luca-dex** [comment]
Negli ultimi invii massivi abbiamo avuto ancora problemi, però sicuramente la situazione è migliorata. Ciononostante, all'ultimo invio massivo sulla Lombardia (oltre 20mila persone) le email sono arrivate 3 volte.

**Comment by yakky** [comment]
@luca-dex quindi il problema sembrerebbe comunque limitato agli invii massivi, è corretto?

**Comment by AlfioEmanueleFresta** [comment]
Si. Qui ha senso fare un ragionamento in termine di code e smistatori.

**Comment by fmarco** [comment]
@luca-dex @AlfioEmanueleFresta @yakky come vogliamo procedere?

**Comment by PaoloGiustiniani** [comment]
@fmarco per ora rimane in "On Hold" non siamo certi che sia risolto il problema.

**Comment by yakky** [comment]
@PaoloGiustiniani ci sono aggiornamenti su questa?

**Comment by luca-dex** [comment]
Io ad ora l'unica problematica ancora riscontrata è quella legata al
timeout.

A volte quando viene spedito una email tutta la Lombardia la pagina va in
timeout, ma le email non arrivano più duplicate.

**Comment by PaoloGiustiniani** [comment]
Il timeout mostra una pagina di cloudflare?

**Comment by yakky** [comment]
@luca-dex ah! la pagina va in timeout! Questo spiega un sacco di cose sulle email duplicate ...
@AlfioEmanueleFresta secondo me si potrebbe usare celery e aggiungere un metodo del tipo ``Messaggio.costruisci_async`` che non fa altro che richiamare ``Messaggio.costruisci`` dentro una coda celery. Se anche l'invio è già asincrono, questa riga https://github.com/CroceRossaItaliana/jorvik/blob/master/posta/models.py#L400 non lo è, e potrebbe essere sicuramente causa del timeout se ci sono invii con 20000 destinatari

**Comment by luca-dex** [comment]
Niente cloudflare, classica pagina di timeout del browser

**Comment by yakky** [comment]
@AlfioEmanueleFresta cosa ne pensi di https://github.com/CroceRossaItaliana/jorvik/issues/345#issuecomment-305137409

**Comment by luca-dex** [comment]
@AlfioEmanueleFresta rispondi al commento di @yakky please?

**Comment by AlfioEmanueleFresta** [comment]
@yakky Celery ❤️. Nel mulino che vorrei anche lo smistamento di posta viene gestito con una coda celery... sentiti libero di aggiungerlo come requisito.

Una cosa che mi preoccupa, a dire il vero, e' l'aggiunta del requisito di un backend di coda -- attualmente non abbiamo niente e bisognerebbe installare qualcosa come redis su tutte le macchine (oltre che aggiornare script di provisioning e README vari). Visto che si tratta di pochi task relativi al mettere in coda i messaggi, possiamo usare qualche backend senza configurazione, come non saprei, sfruttare il db gia' configurato postgres (con qualche migrazione apposita)?

/cc @luca-dex
