### ISSUE TITLE
[turni] attività ha turni multipli ma è mostrata una volta in calendario

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#390]
l'attività 12812 ha multipli turni ma è mostrata sul calendario soltanto l'8 ottobre

**Comment by yakky** [comment]
Non possiamo fare attività di debug ulteriore senza accesso ai dati o a dei log dettagliati dell'errore risultante

**Comment by PaoloGiustiniani** [comment]
@yakky io visualizzo questo (in modifica attività però).

@AlfioEmanueleFresta da quello che ho potuto notare gli utenti non la visualizzano esclusivamente sul calendario, se invece accedono diretti all'attività dalla sezione turni si visualizza tutto. Mi pare che in passato sia già successo.

```
Stack trace
attivita.models:DoesNotExist: Partecipazione matching query does not exist.
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 118, in _pagina_privata
File "./attivita/viste.py", line 699, in attivita_scheda_turni_modifica
File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 122, in manager_method
File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 387, in get
```

**Comment by AlfioEmanueleFresta** [comment]
Da breve investigazione, credo abbia a che fare con i problemi in esplorazione dell'albero dei Comitati. Direi di riverificare la problematica una volta ricostruito l'albero in produzione.

**Comment by fmarco** [comment]
@PaoloGiustiniani @matthewmazzoleni Ci sono novità? Avete avuto modo di fare delle prove (mi riferisco al commento di @AlfioEmanueleFresta )?

**Comment by fmarco** [comment]
@matthewmazzoleni è ancora valida questa segnalazione?
