### ISSUE TITLE
[contatti] apertura pagina genera errore 500 (per tutti)

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#451]
la pagina https://gaia.cri.it/utente/contatti/ attualmente genera errore 500 per chiunque

**Comment by yakky** [comment]
@matthewmazzoleni lo prendo in carico subito, a breve dovrebbe essere pronto il fix

**Comment by AlfioEmanueleFresta** [comment]
```
builtins:KeyError

/utente_contatti

7:55 pm

Time

gaia.cri.it(Gaia Jorvik)

Count
3 similar errors to this in the last 30 minutes


builtins:KeyError: 'accesso'
Stack trace
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 117, in _pagina_privata
File "./anagrafica/viste.py", line 484, in utente_contatti

```

**Comment by yakky** [comment]
@CroceRossaItaliana/infrastruttura merge del fix fatto, potete fare il deploy

**Comment by yakky** [comment]
Comunque è anche su luke, per test pre-deploy
