### ISSUE TITLE
[contatti] Errore 500 - Bloccante

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#453]
/utente_contatti

Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 117, in _pagina_privata
File "./anagrafica/viste.py", line 484, in utente_contatti

**Comment by yakky** [comment]
@PaoloGiustiniani E' corretto da #452 che è già mergiata, ma vedo che produzione non è stato allineato

**Comment by PaoloGiustiniani** [comment]
Provvedo, grazie.
