### ISSUE TITLE
[verifica-email] errore 500 - bloccante

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#454]
Ci viene comunicato che cliccando sulla mail ricevuta in fase di iscrizione (https://gaia.cri.it/registrati/aspirante/anagrafica/?code=xxx) viene mostrato errore 500.

Presumo che lo strace corretto sia

Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 73, in _pagina_anonima
File "./anagrafica/viste.py", line 188, in registrati
File "./posta/models.py", line 334, in invia_raw
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/function_trace.py", line 110, in literal_wrapper
File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 292, in send
File "/usr/local/lib/python3.4/dist-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
File "/usr/local/lib/python3.4/dist-packages/django/core/mail/backends/smtp.py", line 123, in _send
File "/usr/lib/python3.4/smtplib.py", line 792, in sendmail

**Comment by yakky** [comment]
Non si riesce a riprodurre l'errore. Riusciresti a fornire anche l'errore specifico ritornato?

**Comment by PaoloGiustiniani** [comment]
Ti ho inviato il tutto via email.

**Comment by yakky** [comment]
@PaoloGiustiniani avrei bisogno del traceback completo con l'eccezione (tipicamente viene riportata in cima).
L'errore sembra legato con quale problema con l'indirizzo email

**Comment by yakky** [comment]
Il problema è che l'utente eseguiva un flusso non corretto, facendo la registrazione da un PC e proseguendola da un altro.
La soluzione di questo problema è intercettare quando la sessione non è valida e presentare una pagina di errore "di Gaia" spiegando l'origine del problema

**Comment by PaoloGiustiniani** [comment]
> Il problema è che l'utente eseguiva un flusso non corretto, facendo la registrazione da un PC e proseguendola da un altro.

@AlfioEmanueleFresta come mai è stato progettato in questo modo?

**Comment by AlfioEmanueleFresta** [comment]
Pur mantenendo la memorizzazione in sessione, non e' possibile includere il token di sessione in e-mail? Cosi' che la vista controlli il token, verifichi che sia valido e effettivamente contenga una registrazione da completare, ed eventualmente lo sostituisca alla sessione attuale?

**Comment by yakky** [comment]
@AlfioEmanueleFresta se "carichiamo" la sessione via email vedo diversi modi per sfruttare la cosa per creare degli attacchi di sicurezza di impersonation

**Comment by AlfioEmanueleFresta** [comment]
@yakky ad esempio? Il click di validazione dovrebbe semplicemente completare la registrazione, non fare automaticamente il login. La sessione non dovrebbe essere 'autenticata' attraverso l'e-mail.

**Comment by yakky** [comment]
@AlfioEmanueleFresta allora non ho capito :)
Se i dati sono memorizzati in sessione è necessario che il link dell'email carichi quella specifica sessione per poter accedere a quei dati

**Comment by AlfioEmanueleFresta** [comment]
@yakky perdonami, non sono stato chiaro. Con

> La sessione non dovrebbe essere 'autenticata' attraverso l'e-mail.

Intendo che il cliccare sull'e-mail non dovrebbe far avvenire il login, solo avviare la sessione. La sessione dovrebbe rimanere anonima, ovvero non associata ad una utenza, quindi non 'autenticata'. 

Insomma, il click sul link in e-mail dovrebbe solamente confermare l'e-mail e completare la registrazione, ma portare comunque alla pagina di login per far accedere l'utente.

**Comment by yakky** [comment]
La PR allegata dovrebbe risolvere caricando dinamicamente la sessione con qualche check di sicurezza

**Comment by PaoloGiustiniani** [comment]
@alfioemanuele questa possiamo testarla in produzione, se acconsenti mergiamo
