### ISSUE TITLE
[reclama] errore 500 

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#469]
Segnalo che sono presenti errori 500 in fase di reclama persona

Error message

ufficio_soci.models:DoesNotExist: Tesseramento matching query does not exist.
Stack trace
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 117, in _pagina_privata
File "./ufficio_soci/viste.py", line 131, in us_reclama_persona
File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 122, in manager_method
File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 387, in get

Se servissero dettagli per replicare fatemi sapere.

**Comment by yakky** [comment]
@PaoloGiustiniani potrebbe non essere stato creato il tesseramento per l'anno 2017 nell'admin

**Comment by PaoloGiustiniani** [comment]
Aperto, grazie.
