### ISSUE TITLE
[cron] bloccati dopo rilascio di #442 (BLOCCANTE)

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#498]
Dopo il rilascio di #442 si è bloccata l'esecuzione del cron della posta e quello denominato "base.estensioni.notifica.manuali" va in errore ogni  5 minuti 

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django_cron/management/commands/runcrons.py", line 62, in run_cron_with_cache_check
    manager.run(force)
  File "/usr/local/lib/python3.4/dist-packages/django_cron/__init__.py", line 214, in run
    self.msg = self.cron_job.do()
  File "/home/gaia/jorvik/base/cron.py", line 40, in do
    Autorizzazione.notifiche_richieste_in_attesa()
  File "/home/gaia/jorvik/base/models.py", line 351, in notifiche_richieste_in_attesa
    scadenza__isnull=False, scadenza__gt=now().exclude(tipo_gestione=Autorizzazione.MANUALE)
AttributeError: 'datetime.datetime' object has no attribute 'exclude'

**Comment by AlfioEmanueleFresta** [comment]
@yakky Come e' passato in produzione senza accendere alcuna spia rossa?

**Comment by AlfioEmanueleFresta** [comment]
Come non detto, ho visto che e' saltato il commit coi test funzionali. Niente di grave -- cerchiamo solo di assicurarci non succeda nuovamente.

**Comment by yakky** [comment]
@AlfioEmanueleFresta concordo. E' il problema della PR che rimangono aperte troppo a lungo, purtroppo. Con i rebase e i forwardport i rischi di perdeere pezzi aumentano :cry:

**Comment by AlfioEmanueleFresta** [comment]
Fair enough

**Comment by PaoloGiustiniani** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django_cron/management/commands/runcrons.py", line 62, in run_cron_with_cache_check
    manager.run(force)
  File "/usr/local/lib/python3.4/dist-packages/django_cron/__init__.py", line 214, in run
    self.msg = self.cron_job.do()
  File "/home/gaia/jorvik/base/cron.py", line 28, in do
    Autorizzazione.gestisci_automatiche()
  File "/home/gaia/jorvik/base/models.py", line 330, in gestisci_automatiche
    autorizzazione.controlla_nega_automatico()
  File "/home/gaia/jorvik/base/models.py", line 314, in controlla_nega_automatico
    self.nega(auto=True)
  File "/home/gaia/jorvik/base/models.py", line 209, in nega
    self.firma(firmatario, False, modulo=modulo, auto=auto)
  File "/home/gaia/jorvik/base/models.py", line 181, in firma
    self.oggetto.confermata = False
AttributeError: 'NoneType' object has no attribute 'confermata'

**Comment by yakky** [comment]
un'autorizzazione senza oggetto collegato ...

**Comment by yakky** [comment]
@AlfioEmanueleFresta ti risulta che sia possibile? o è un'anomalia da gestire con un'eccezione?

**Comment by yakky** [comment]
@PaoloGiustiniani questo si può chiudere?

**Comment by PaoloGiustiniani** [comment]
@yakky si, mi indichi dove logghiamo?

**Comment by yakky** [comment]
fa un print, quindi dovrebbe uscire nei log del cron (immagino email)

**Comment by PaoloGiustiniani** [comment]
ok
