### ISSUE TITLE
[corsi] errore 500 su scaricamento liste

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#592]
sullo scaricamento liste iscritti al corso otteniamo errore 500.
la persona che ha effettuato la segnalazione è 7966 e il corso è il 41/2017

**Comment by PaoloGiustiniani** [comment]
@CroceRossaItaliana/sviluppo 

Error message
django.db.models.fields.related_descriptors:RelatedObjectDoesNotExist: Persona has no aspirante.

Stack trace
django.db.models.fields.related_descriptors:RelatedObjectDoesNotExist: Persona has no aspirante.
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 119, in _pagina_privata
File "./ufficio_soci/viste.py", line 645, in us_elenco_download
File "./ufficio_soci/viste.py", line 645, in <listcomp>
File "./formazione/elenchi.py", line 15, in <lambda>
File "/usr/local/lib/python3.4/dist-packages/django/db/models/fields/related_descriptors.py", line 355, in __get__

**Comment by yakky** [comment]
@PaoloGiustiniani @matthewmazzoleni provate a controllare se si verifica tutt'ora dopo il deploy del fix a #356
