### ISSUE TITLE
[attività] iscrizione dell'utente genera errore 500

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#593]
la persona 2845 iscrivendosi all'attività "public speaking" riceve errore 500, il problema sembra specifico di alcuni utenti e non generalizzato su tutti (quindi ci sono condizioni che generano l'errore)

**Comment by PaoloGiustiniani** [comment]
@matthewmazzoleni 2845 è dimesso

**Comment by matthewmazzoleni** [comment]
@PaoloGiustiniani rettifico: 28458

**Comment by PaoloGiustiniani** [comment]
@CroceRossaItaliana/sviluppo 

builtins:UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 60: ordinal not in range(128)

Stack trace
builtins:UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 60: ordinal not in range(128)
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 119, in _pagina_privata
File "./attivita/viste.py", line 507, in attivita_scheda_turni_partecipa
File "./attivita/models.py", line 630, in richiedi
File "./base/models.py", line 744, in autorizzazione_richiedi
