### ISSUE TITLE
[Trasferimento] Errore 500

### ISSUE THREAD

**Issue by Ele81** [CroceRossaItaliana/jorvik#598]
Registrazione del trasferimento per un volontario genera errore 500.
Il trasferimento è stato inserito dall' utente 5809 per ID=60738
La richiesta di trasferimento viene generata (ora e data di creazione 29/05/2017 13:04:06)

**Comment by PaoloGiustiniani** [comment]
1:44 pm
TIME
gaia.cri.it(Gaia Jorvik)
INSTANCE
1
COUNT
1 similar error to this
in the last 6 hours
Error message
builtins:UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 60: ordinal not in range(128)

Stack trace
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 119, in _pagina_privata
File "./anagrafica/viste.py", line 873, in utente_trasferimento
File "./anagrafica/models.py", line 2040, in richiedi
File "./base/models.py", line 673, in autorizzazione_richiedi_sede_riferimento
File "./base/models.py", line 744, in autorizzazione_richiedi

**Comment by yakky** [comment]
L'errore nasce in questo ``print`` https://github.com/CroceRossaItaliana/jorvik/blob/master/base/models.py#L743 che serve solo per debug
Ci potrebbe essere un nome di persona con caratteri strani, ma è strano un errore simile su python 3.
Un quickfix è commentare quella linea e forse avere un meccanismo di loggin strutturato per questi messaggi di debug
cc @AlfioEmanueleFresta

**Comment by AlfioEmanueleFresta** [comment]
@yakky oops, decisamente --  non dovremmo generare output a `stdout`/`stderr` meno che necessario.

**Comment by AlfioEmanueleFresta** [comment]
> @yakky: Ci potrebbe essere un nome di persona con caratteri strani, ma è strano un errore simile su python 3.

Giusto, ma non giustissimo -- Purtroppo per quanto Python 3 di default usi UTF-8, il problema sta nell'encoding di stdin/stdout forzato con `PYTHONIOENCODING=ascii`. E' appunto `ascii` che non e' lo standard di sistema per via dell'interazione tramite uwsgi.
