### ISSUE TITLE
[cron] KO base.estensioni.notifica.manuali

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#651]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django_cron/management/commands/runcrons.py", line 62, in run_cron_with_cache_check
    manager.run(force)
  File "/usr/local/lib/python3.4/dist-packages/django_cron/__init__.py", line 214, in run
    self.msg = self.cron_job.do()
  File "/home/gaia/jorvik/base/cron.py", line 41, in do
    Autorizzazione.notifiche_richieste_in_attesa()
  File "/home/gaia/jorvik/base/models.py", line 382, in notifiche_richieste_in_attesa
    print('autorizzazione {} non ha oggetto collegato'.format(autorizzazione.ok))
AttributeError: 'Autorizzazione' object has no attribute 'ok'

**Comment by yakky** [comment]
@PaoloGiustiniani è un typo che mi era sfuggito
aperta PR se non vedo errori insoliti nei test faccio il merge ed è deployabile

**Comment by luca-dex** [comment]
ok
